---
name: Test

on:
  pull_request:
    branches:      
      - main              
      - develop
  workflow_call:
  workflow_dispatch:

jobs:
  
  test-auth-unit:
    name: Tests Auth.UnitTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: Auth.UnitTests
      test_path: Services/AuthService/Auth.UnitTests
      
  test-auth-integration:
    name: Tests Auth.IntegrationTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: Auth.IntegrationTests
      test_path: Services/AuthService/Auth.IntegrationTests
  
  test-storage-unit:
    name: Tests Storage.UnitTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: Storage.UnitTests
      test_path: Services/StorageService/Storage.UnitTests
      
  test-storage-integration:
    name: Tests Storage.IntegrationTests
    uses: Red-Papers-Studio/.github/.github/workflows/dotnet_test.yml@main
    with:
      dotnet_version: 6.0.x
      project_name: Storage.IntegrationTests
      test_path: Services/StorageService/Storage.IntegrationTests
